use crate::error::{Error, Result};
use std::collections::HashMap;
use crate::intern::Symbol;
use crate::parser::ast::*;
use crate::span::Span;
use crate::hir::*;
use super::helpers::*;
use super::{FnSig, InterfaceReg, Ctx};

mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod ensure;
mod part_10;
mod collect_enum;
mod collect_import;
mod expr_access;
mod expr_call;
mod expr_call_extra;
mod expr_enum;
mod expr_misc;
mod expr_ops1;
