use crate::error::{Error, Result};
use std::collections::HashMap;
use crate::intern::Symbol;
use crate::parser::ast::*;
use crate::span::Span;
use crate::hir::*;
use super::helpers::*;
use super::{FnSig, InterfaceReg, Ctx};

mod collect_fns;
mod collect_ns;
mod vtables;
mod iface_match;
mod overload_resolve;
mod generic_specialize;
mod lower_items;
mod stmt_lower;
mod ref_assign;
mod expr_method;
mod match_lower;
mod usage_infer;
mod macro_call;
mod expr_lower;
mod ensure;
mod literal;
mod collect_enum;
mod collect_import;
mod expr_access;
mod expr_call;
mod expr_call_extra;
mod block_lower;
mod expr_cast;
mod expr_enum;
mod expr_misc;
mod expr_ops1;
