use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Keyword {
    Null,
    Pub,
    Crate,
    Inline,
    Extern,
    Asm,
    Out,
    Reg,
    Clobbers,
    Import,
    Fn,
    Return,
    For,
    Break,
    Continue,
    If,
    Elif,
    Else,
    In,
    While,
    Int,
    Float,
    Char,
    Bool,
    Ref,
    Mut,
    Shared,
    Unique,
    Weak,
    Namespace,
    Struct,
    Move,
    Clone,
    Interface,
    Impl,
    Self_,
    True,
    False,
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Keyword::Null => "null",
            Keyword::Pub => "pub",
            Keyword::Crate => "crate",
            Keyword::Inline => "inline",
            Keyword::Extern => "extern",
            Keyword::Asm => "asm",
            Keyword::In => "in",
            Keyword::Out => "out",
            Keyword::Reg => "reg",
            Keyword::Clobbers => "clobbers",
            Keyword::Import => "import",
            Keyword::Fn => "fn",
            Keyword::Return => "return",
            Keyword::For => "for",
            Keyword::Break => "break",
            Keyword::Continue => "continue",
            Keyword::If => "if",
            Keyword::Elif => "elif",
            Keyword::Else => "else",
            Keyword::While => "while",
            Keyword::Int => "int",
            Keyword::Float => "float",
            Keyword::Char => "char",
            Keyword::Bool => "bool",
            Keyword::Ref => "ref",
            Keyword::Mut => "mut",
            Keyword::Shared => "shared",
            Keyword::Unique => "unique",
            Keyword::Weak => "weak",
            Keyword::Namespace => "namespace",
            Keyword::Struct => "struct",
            Keyword::Move => "move",
            Keyword::Clone => "clone",
            Keyword::Interface => "interface",
            Keyword::Impl => "impl",
            Keyword::Self_ => "self",
            Keyword::True => "true",
            Keyword::False => "false",
        };
        write!(f, "{}", s)
    }
}
